# Pytorch Overview

In [17]:
import torch
import pandas as pd

In [18]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [19]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
tensor = torch.Tensor([[1,2,3],[4,5,6]])
tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
tensor * 5

tensor([[ 5., 10., 15.],
        [20., 25., 30.]])

Tensors are analogous to numpy arrays in many ways.

In [22]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [23]:
X, y = load_breast_cancer(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled_tensor = torch.from_numpy(X_train_scaled).float()
X_test_scaled_tensor = torch.from_numpy(X_test_scaled).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [25]:
train_dataset = TensorDataset(X_train_scaled_tensor, y_train_tensor)

In [26]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [27]:
class BCNet(nn.Module):
    def __init__(self):
        super(BCNet, self).__init__()

        self.fc1 = nn.Linear(30, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)

        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = F.sigmoid(self.fc3(x))

        return x

In [28]:
model = BCNet()

In [29]:
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [30]:
epochs = 20

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for x_batch, y_batch in train_loader:
        optimizer.zero_grad()

        preds = model(x_batch)
        loss = criterion(preds, y_batch)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch {epoch+1}: Loss was {running_loss / len(train_loader)}')

Epoch 1: Loss was 0.6796520233154297
Epoch 2: Loss was 0.5880108157793681
Epoch 3: Loss was 0.44844430883725483
Epoch 4: Loss was 0.30545387864112855
Epoch 5: Loss was 0.2071236843864123
Epoch 6: Loss was 0.14513322959343591
Epoch 7: Loss was 0.12585828627149265
Epoch 8: Loss was 0.10375750064849854
Epoch 9: Loss was 0.08393467416365942
Epoch 10: Loss was 0.0833615447084109
Epoch 11: Loss was 0.07472258731722832
Epoch 12: Loss was 0.05719299037009477
Epoch 13: Loss was 0.07555795547862848
Epoch 14: Loss was 0.0530075807745258
Epoch 15: Loss was 0.05742819930116336
Epoch 16: Loss was 0.06010964214801788
Epoch 17: Loss was 0.05139638675997655
Epoch 18: Loss was 0.04695587037907292
Epoch 19: Loss was 0.05064138217518727
Epoch 20: Loss was 0.044661614826569954


In [31]:
with torch.no_grad():
    model.eval()

    preds = model(X_test_scaled_tensor)
    loss = criterion(preds, y_test_tensor).item()

    accuracy = ((preds >= 0.5) == y_test_tensor).float().mean().item()

In [32]:
accuracy

0.9736841917037964